name: Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.HOST }}

    strategy:
      matrix:
        CXX_STD: [ 14, 17 ]
        HOST: [ubuntu-22.04, windows-2022]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STD }}

      - name: Build
        run: cmake --build build --config Release -j 6
